import Link from "next/link";

export const metadata = {
  title: "Privacy Policy — Memori",
  description: "Memori privacy policy. Your data stays on your device.",
};

export default function PrivacyPolicy() {
  return (
    <div className="min-h-screen">
      <nav className="fixed top-0 z-50 w-full border-b border-white/5 bg-page-bg/80 backdrop-blur-xl">
        <div className="mx-auto flex h-14 max-w-6xl items-center px-6">
          <Link href="/" className="flex items-center gap-2.5">
            <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-accent text-xs font-black text-white">M</div>
            <span className="text-base font-bold text-text-primary">Memori</span>
          </Link>
        </div>
      </nav>

      <main className="mx-auto max-w-3xl px-6 pt-28 pb-24">
        <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-teal/20 bg-teal/5 px-4 py-1.5">
          <span className="text-xs font-bold text-teal">Your data stays on your device</span>
        </div>

        <h1 className="mb-2 text-3xl font-black text-text-primary">Privacy Policy</h1>
        <p className="mb-10 text-sm font-medium text-text-tertiary">Last updated: March 6, 2026</p>

        <div className="space-y-8 text-text-secondary leading-relaxed [&_h2]:mb-3 [&_h2]:mt-8 [&_h2]:text-lg [&_h2]:font-bold [&_h2]:text-text-primary [&_strong]:text-text-primary [&_ul]:ml-6 [&_ul]:list-disc [&_ul]:space-y-1">
          <section>
            <h2>Our Core Principle</h2>
            <p><strong>Your data stays on your device. Always.</strong> Memori is designed with privacy as a fundamental principle, not an afterthought. We do not collect, store, or transmit your personal data to any server.</p>
          </section>

          <section>
            <h2>Data Storage</h2>
            <p>All data generated by using Memori is stored locally on your device using Apple&apos;s SwiftData framework. This includes:</p>
            <ul>
              <li>Brain Score assessment results</li>
              <li>Exercise history and scores</li>
              <li>Streak and achievement data</li>
              <li>User preferences and settings</li>
            </ul>
            <p className="mt-3">This data never leaves your device unless you explicitly choose to share it (e.g., sharing a score card with friends).</p>
          </section>

          <section>
            <h2>No Accounts Required</h2>
            <p>Memori does not require you to create an account, provide an email address, or sign in with any service. There is no user registration process.</p>
          </section>

          <section>
            <h2>No Analytics or Tracking</h2>
            <p>We do not use any third-party analytics services, advertising SDKs, or tracking tools. We do not collect usage metrics, crash reports, or behavioral data.</p>
          </section>

          <section>
            <h2>Apple Services</h2>
            <p>Memori integrates with the following Apple services, which are governed by Apple&apos;s own privacy policies:</p>
            <ul>
              <li><strong>Game Center:</strong> If you choose to sign in to Game Center, your scores may be shared on leaderboards. This is managed entirely by Apple.</li>
              <li><strong>StoreKit / In-App Purchases:</strong> Subscription purchases are processed by Apple. We do not have access to your payment information.</li>
              <li><strong>Notifications:</strong> If you enable notifications, they are scheduled locally on your device. No data is sent to external push notification services.</li>
            </ul>
          </section>

          <section>
            <h2>Data Sharing</h2>
            <p>Memori includes share features that let you share your Brain Score and challenge cards with friends. When you use these features, the shared content is handled by iOS&apos;s built-in share sheet. We have no involvement in or access to this sharing process.</p>
          </section>

          <section>
            <h2>Data Deletion</h2>
            <p>You can delete all your data at any time from Settings → Reset All Data within the app. Uninstalling the app will also remove all locally stored data.</p>
          </section>

          <section>
            <h2>Children&apos;s Privacy</h2>
            <p>Memori is not directed at children under the age of 13. We do not knowingly collect any information from children.</p>
          </section>

          <section>
            <h2>Changes to This Policy</h2>
            <p>We may update this privacy policy from time to time. Any changes will be reflected on this page with an updated date.</p>
          </section>

          <section>
            <h2>Contact</h2>
            <p>If you have questions about this privacy policy, contact us at <a href="mailto:dylanbryanmiller@gmail.com" className="font-bold text-accent underline">dylanbryanmiller@gmail.com</a>.</p>
          </section>
        </div>
      </main>
    </div>
  );
}
